// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWEmBOdLwhKh8t3nTQ_U80hYYbe_jb3Zc',
    appId: '1:1063586552091:web:34ab2ca6e926702f54dbbe',
    messagingSenderId: '1063586552091',
    projectId: 'movie-app-c668d',
    authDomain: 'movie-app-c668d.firebaseapp.com',
    storageBucket: 'movie-app-c668d.appspot.com',
    measurementId: 'G-MYGC8JRLQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpCOms7TKrxZiHdvg22vYuKGwbrN1k8No',
    appId: '1:1063586552091:android:ce8d764058187ff454dbbe',
    messagingSenderId: '1063586552091',
    projectId: 'movie-app-c668d',
    storageBucket: 'movie-app-c668d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-UsU1QJDMAF60ZS8z337edMKG6bBYYMY',
    appId: '1:1063586552091:ios:f4de601af6cd1e2d54dbbe',
    messagingSenderId: '1063586552091',
    projectId: 'movie-app-c668d',
    storageBucket: 'movie-app-c668d.appspot.com',
    iosBundleId: 'com.example.cinemaxMovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-UsU1QJDMAF60ZS8z337edMKG6bBYYMY',
    appId: '1:1063586552091:ios:f4de601af6cd1e2d54dbbe',
    messagingSenderId: '1063586552091',
    projectId: 'movie-app-c668d',
    storageBucket: 'movie-app-c668d.appspot.com',
    iosBundleId: 'com.example.cinemaxMovieApp',
  );
}
