// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv4frFdSzi_brcnqEWNfDP_AYNWlVrt8o',
    appId: '1:295418757661:web:d1a1619e18ca9c69d9fcf4',
    messagingSenderId: '295418757661',
    projectId: 'cinemax-movie-app',
    authDomain: 'cinemax-movie-app.firebaseapp.com',
    storageBucket: 'cinemax-movie-app.appspot.com',
    measurementId: 'G-3JEG4FYGG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgrhUSmm7mGWNQ_T4M4THxODtMXrGghao',
    appId: '1:295418757661:android:7a2bb6bb0740a6add9fcf4',
    messagingSenderId: '295418757661',
    projectId: 'cinemax-movie-app',
    storageBucket: 'cinemax-movie-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDxHKtH4ES6-8VlwJJrJAix4PMpJadzoE',
    appId: '1:295418757661:ios:b114736a0880c1c6d9fcf4',
    messagingSenderId: '295418757661',
    projectId: 'cinemax-movie-app',
    storageBucket: 'cinemax-movie-app.appspot.com',
    iosBundleId: 'com.example.cinemaxMovieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDxHKtH4ES6-8VlwJJrJAix4PMpJadzoE',
    appId: '1:295418757661:ios:b114736a0880c1c6d9fcf4',
    messagingSenderId: '295418757661',
    projectId: 'cinemax-movie-app',
    storageBucket: 'cinemax-movie-app.appspot.com',
    iosBundleId: 'com.example.cinemaxMovieApp',
  );
}
